name: "workflow_1 for trigger build"
on:
  push:
    branches: [ "dev/3.0.0" ]
  pull_request:
    branches: [ "dev/3.0.0" ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: |
          curl -X POST https://api.github.com/repos/Workspace-Docker-ContainerMC/velocity_container/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.WORKFLOW_TOKEN }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - uses: actions/checkout@v4
